### ISSUE TITLE
pymatgen 2019.5.8 breaks pysodistort

### ISSUE THREAD

**Issue by jkshenton** [jrbp/pysotropy#1]
Hi! 

Thanks for making such a useful package -- it's well needed in the community!

I've run into some issues with my version of pymatgen, however, and don't really want to downgrade it (incidentally, which version of pmg works for you?).

The main thing it seems to complain about is that the rh_only option no longer exists in the get_transformation method of StructureMatcher. Commenting that out makes the script run, but it finds a left-handed basis for your example in the README and then the results I get no longer make sense. 

Any ideas of how to fix this? 

Cheers,
Kane

**Comment by jrbp** [comment]
Thank you for your interest!
Sorry that it took so long for me to get back to you.

I added the rh_only parameter in my fork of pymatgen. If you want to try a hacky solution you could modify your version of pymatgen following my commit: jrbp/pymatgen@c587ac98b47402b1e172eaf79be32395c321eae6. This was done with pymatgen 2018.9.30 (I should test my code against newer versions). Ignore the change to structrure_vtk that should have been a seperate commit.

I will look in to submitting a pull request to pymatgen and see if there is interest in including this in future versions. If not, I will find a way to move the functionality in to my code.

**Comment by jrbp** [comment]
This is fixed for now by patching pymatgen at runtime since ﻿I don't want to submit a pull request until this is a bit more polished. The patch shouldn't interfere with pymatgen in any way since all it does is add an optional argument (rh_only) which has a default value that reproduces pymatgens behavior.
